import {
  MaintenanceStatus,
  MaintenanceType,
} from '../schemas/maintenance.schema';

export const maintenanceSeeds = [
  {
    title: 'Nâng cấp Database',
    description: 'Nâng cấp hệ thống database lên phiên bản mới nhất',
    startTime: new Date('2025-10-25T10:00:00Z'),
    endTime: new Date('2025-10-25T12:00:00Z'),
    status: MaintenanceStatus.SCHEDULED,
    type: MaintenanceType.DATABASE,
    isActive: false,
    autoAdjusted: false,
  },
  {
    title: 'Bảo trì Hệ thống',
    description: 'Bảo trì định kỳ hệ thống và cập nhật các tính năng mới',
    startTime: new Date('2025-10-26T14:00:00Z'),
    endTime: new Date('2025-10-26T18:00:00Z'),
    status: MaintenanceStatus.SCHEDULED,
    type: MaintenanceType.SYSTEM,
    isActive: false,
    autoAdjusted: false,
  },
  {
    title: 'Nâng cấp Network',
    description: 'Nâng cấp hạ tầng mạng và bảo mật',
    startTime: new Date('2025-10-27T22:00:00Z'),
    endTime: new Date('2025-10-28T02:00:00Z'),
    status: MaintenanceStatus.SCHEDULED,
    type: MaintenanceType.NETWORK,
    isActive: false,
    autoAdjusted: false,
  },
  {
    title: 'Cập nhật Phần mềm',
    description: 'Cập nhật các phần mềm hệ thống lên phiên bản mới',
    startTime: new Date('2025-10-29T08:00:00Z'),
    endTime: new Date('2025-10-29T10:00:00Z'),
    status: MaintenanceStatus.SCHEDULED,
    type: MaintenanceType.OTHER,
    isActive: false,
    autoAdjusted: false,
  },
  {
    title: 'Bảo trì Khẩn cấp',
    description: 'Sửa chữa lỗi hệ thống khẩn cấp',
    startTime: new Date('2025-10-24T09:00:00Z'),
    endTime: new Date('2025-10-24T11:00:00Z'),
    status: MaintenanceStatus.COMPLETED,
    type: MaintenanceType.SYSTEM,
    isActive: false,
    autoAdjusted: false,
    duration: 120,
  },
  {
    title: 'Nâng cấp Server',
    description: 'Nâng cấp phần cứng và phần mềm server',
    startTime: new Date('2025-10-23T20:00:00Z'),
    endTime: new Date('2025-10-24T02:00:00Z'),
    status: MaintenanceStatus.COMPLETED,
    type: MaintenanceType.SYSTEM,
    isActive: false,
    autoAdjusted: false,
    duration: 360,
  },
  {
    title: 'Bảo trì Backup System',
    description: 'Kiểm tra và tối ưu hệ thống backup',
    startTime: new Date('2025-10-22T15:00:00Z'),
    endTime: new Date('2025-10-22T17:00:00Z'),
    status: MaintenanceStatus.CANCELLED,
    type: MaintenanceType.DATABASE,
    isActive: false,
    autoAdjusted: false,
  },
  {
    title: 'Cập nhật SSL',
    description: 'Cập nhật chứng chỉ SSL cho hệ thống',
    startTime: new Date('2025-10-21T12:00:00Z'),
    endTime: new Date('2025-10-21T13:00:00Z'),
    status: MaintenanceStatus.COMPLETED,
    type: MaintenanceType.NETWORK,
    isActive: false,
    autoAdjusted: false,
    duration: 60,
  },
  {
    title: 'Tối ưu Database',
    description: 'Tối ưu hiệu suất và dọn dẹp database',
    startTime: new Date('2025-10-20T23:00:00Z'),
    endTime: new Date('2025-10-21T01:00:00Z'),
    status: MaintenanceStatus.COMPLETED,
    type: MaintenanceType.DATABASE,
    isActive: false,
    autoAdjusted: false,
    duration: 120,
  },
  {
    title: 'Nâng cấp Security',
    description: 'Cập nhật các tính năng bảo mật mới',
    startTime: new Date('2025-10-19T18:00:00Z'),
    endTime: new Date('2025-10-19T20:00:00Z'),
    status: MaintenanceStatus.COMPLETED,
    type: MaintenanceType.NETWORK,
    isActive: false,
    autoAdjusted: false,
    duration: 120,
  },
];
